arch = "AArch64"
name = "CoWinvT.EL1+tlbidsb-isb"
orig = "PosWT(VAE1) DSB.SY+ISBsT(VAE1)R Tfrib"
symbolic = ["pa_0_va_0"]

page_table_setup = """
    physical pa_0;
    pa_0_va_0 |-> pa_0;
    pa_0_va_0 ?-> invalid;
    *pa_0 = 0;
    identity 0x1000 with code;
"""

[thread.0]
code = """
    STR X0,[X1]
    TLBI VAE1,X2
    DSB SY
    ISB
    LDR X3,[X4]
"""

[thread.0.reset]
R0 = "extz(0x0, 64)"
R1 = "pte3(pa_0_va_0, page_table_base)"
R2 = "extz(page(pa_0_va_0), 64)"
R3 = "extz(0x0, 64)"
R4 = "pa_0_va_0"

VBAR_EL1 = "extz(0x1000, 64)"

"PSTATE.EL" = "0b01"

[section.thread0_el1_handler]
address = "0x1000"
code = """
    MOV X3,#1

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
assertion = "0:X3 = 0"
