arch = "AArch64"
name = "CoWR.alias"
orig = "PoaWR Frai"
symbolic = ["pa_0_va_0", "pa_0_va_1"]

page_table_setup = """
    physical pa_0;
    pa_0_va_0 |-> pa_0;
    pa_0_va_1 |-> pa_0;
    *pa_0 = 0;
"""

[thread.0]
code = """
    STR X0,[X1]
    LDR X2,[X3]
"""

[thread.0.reset]
R0 = "extz(0x1, 64)"
R1 = "pa_0_va_0"
R2 = "extz(0x0, 64)"
R3 = "pa_0_va_1"

[final]
assertion = "0:X2 = 0"
