arch = "AArch64"
name = "MP.alias+pos"
orig = "PoaWW Rfe PoaRR Fre"
symbolic = ["pa_0_va_0", "pa_0_va_1"]

page_table_setup = """
    physical pa_0;
    pa_0_va_0 |-> pa_0;
    pa_0_va_1 |-> pa_0;
    *pa_0 = 0;
"""

[types]
"pa_0" = "uint64_t"

[thread.0]
code = """
    LDR X0,[X1]
    LDR X2,[X3]
"""

[thread.0.reset]
R0 = "extz(0x0, 64)"
R1 = "pa_0_va_0"
R2 = "extz(0x0, 64)"
R3 = "pa_0_va_1"

[thread.1]
code = """
    STR X0,[X1]
    STR X2,[X3]
"""

[thread.1.reset]
R0 = "extz(0x1, 64)"
R1 = "pa_0_va_1"
R2 = "extz(0x2, 64)"
R3 = "pa_0_va_0"

[final]
assertion = "*pa_0 = 2 & 0:X0 = 2 & 0:X2 = 0"
