arch = "AArch64"
name = "PPOCA.alias"
orig = "DMB.SYdWW Rfe DpCtrldW Rfai DpAddrdR Fre"
symbolic = ["pa_0_va_0", "pa_1_va_0", "pa_1_va_1", "pa_2_va_0"]

page_table_setup = """
    physical pa_0 pa_1 pa_2;
    pa_0_va_0 |-> pa_0;
    pa_1_va_0 |-> pa_1;
    pa_1_va_1 |-> pa_1;
    pa_2_va_0 |-> pa_2;
    *pa_0 = 0;
    *pa_1 = 0;
    *pa_2 = 0;
"""

[thread.0]
code = """
    LDR X0,[X1]
    CBNZ X0,.+4
    STR X2,[X3]
    LDR X4,[X5]
    EOR X14,X4,X4
    ADD X7,X7,X14
    LDR X6,[X7]
"""

[thread.0.reset]
R0 = "extz(0x0, 64)"
R1 = "pa_0_va_0"
R2 = "extz(0x1, 64)"
R3 = "pa_1_va_0"
R4 = "extz(0x0, 64)"
R5 = "pa_1_va_1"
R6 = "extz(0x0, 64)"
R7 = "pa_2_va_0"

[thread.1]
code = """
    STR X0,[X1]
    DMB SY
    STR X2,[X3]
"""

[thread.1.reset]
R0 = "extz(0x1, 64)"
R1 = "pa_2_va_0"
R2 = "extz(0x1, 64)"
R3 = "pa_0_va_0"

[final]
assertion = "0:X0 = 1 & 0:X4 = 1 & 0:X6 = 0"
