# No, IPAs
arch = "AArch64"
name = "IntermediateTLB"
symbolic = ["x"]

page_table_setup = """
    physical pa1;
    *pa1 = 1;
    x |-> invalid;
    x ?-> pa1;
    x ?-> invalid at level 2;

    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    MOV X2, #0
    STR X2, [X1]
    DSB SY
    STR X4, [X3]
    DSB SY
    ISB
    LDR X6, [X5]
"""

[thread.0.reset]
R1 = "pte2(x,page_table_base)"
R3 = "pte3(x,page_table_base)"
R4 = "mkdesc3(oa=pa1)"
R5 = "x"
VBAR_EL1 = "extz(0x1000, 64)"
"PSTATE.EL" = "0b01"
"PSTATE.SP" = "0b1"
# This test doesn't need stage 2, so I disable stage 2 to make it run faster.
# HCR_EL2 = "extz(0x0,64)"

[section.thread0_el1_handler]
address = "0x1000"
code = """
    MOV X6,#0

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
assertion = "0:X6 = 1"
